package PopStarsPackage;

public class Pruebas {
    public static void main(String[] args) {
        Cantante c1 = new Cantante("Ava Max");
        Cantante c2 = new Cantante("Aitana");
        Cantante c3 = new Cantante("Iggy Azalea");
        Cantante c4 = new Cantante("Halsey");
        Cantante c5 = new Cantante("Alan Walker");
        Cantante c6 = new Cantante("Dua Lipa");
        Cantante c7 = new Cantante("Taylor Swift");
        Cantante c8 = new Cantante("Lady Antebellum");
        Cantante c9 = new Cantante("Ariana Grande");
        Cantante c10 = new Cantante("Lady Gaga");
        Cantante c11 = new Cantante("Pitbull");
        Cantante c12 = new Cantante("Imagine Dragons");
        Cantante c13 = new Cantante("The Weeknd");
        Cantante c14 = new Cantante("Katy Perry");
        Cantante c15 = new Cantante("Ed Sheeran");
        Cantante c16 = new Cantante("Avicii");
        Cantante c17 = new Cantante("Meghan Trainor");
        Cantante c18 = new Cantante("Galantis");
        Cantante c19 = new Cantante("Macklemore");
        Cantante c20 = new Cantante("Maroon 5");
        Cantante c21 = new Cantante("Panic! At the disco");
        Cantante c22 = new Cantante("Jason Derulo");
        Cantante c23 = new Cantante("Whitney Houston");
        Cantante c24 = new Cantante("Ellie Goulding");
        Cantante c25 = new Cantante("Clean Bandit");
        Cantante c26 = new Cantante("Carly Rae Jepsen");
        Cantante c27 = new Cantante("Bebe Rexha");
        Cantante c28 = new Cantante("Anne-Marie");
        Cantante c29 = new Cantante("La 5ª estación");
        Cantante c30 = new Cantante("Sia");
        Cantante c31 = new Cantante("Charlie Puth");
        Cantante c32 = new Cantante("Omi");
        Cantante c33 = new Cantante("Nea");
        Cantante c34 = new Cantante("David Guetta");
        Cantante c35 = new Cantante("Zara Larsson");
        Cantante c36 = new Cantante("James Arthur");
        Cantante c37 = new Cantante("Florida");
        Cantante c38 = new Cantante("Olly Murs");
        Cantante c39 = new Cantante("Fearless Feelings");


        ListaCalificada l = new ListaCalificada();
        l.insertarCantante(c1);
        l.insertarCantante(c2);
        l.insertarCantante(c3);
        l.insertarCantante(c4);
        l.insertarCantante(c5);
        l.insertarCantante(c6);
        l.insertarCantante(c7);
        l.insertarCantante(c8);
        l.insertarCantante(c9);
        l.insertarCantante(c10);
        l.insertarCantante(c11);
        l.insertarCantante(c12);
        l.insertarCantante(c13);
        l.insertarCantante(c14);
        l.insertarCantante(c15);
        l.insertarCantante(c16);
        l.insertarCantante(c17);
        l.insertarCantante(c18);
        l.insertarCantante(c19);
        l.insertarCantante(c20);
        l.insertarCantante(c21);
        l.insertarCantante(c22);
        l.insertarCantante(c23);
        l.insertarCantante(c24);
        l.insertarCantante(c25);
        l.insertarCantante(c26);
        l.insertarCantante(c27);
        l.insertarCantante(c28);
        l.insertarCantante(c29);
        l.insertarCantante(c30);
        l.insertarCantante(c31);
        l.insertarCantante(c32);
        l.insertarCantante(c33);
        l.insertarCantante(c34);
        l.insertarCantante(c35);
        l.insertarCantante(c36);
        l.insertarCantante(c37);
        l.insertarCantante(c38);
        l.insertarCantante(c39);

        Cancion cc1 = new Cancion("Alone", 10);
        Cancion cc2 = new Cancion("Torn", 10);
        Cancion cc3 = new Cancion("Kings & Queens", 10);
        Cancion cc4 = new Cancion("Freaking me out", 9.5);
        Cancion cc5 = new Cancion("Who's laughing now", 9.5);
        Cancion cc6 = new Cancion("Sweet but psycho", 9.5);
        Cancion cc7 = new Cancion("So am I", 9);
        Cancion cc8 = new Cancion("Rumors", 8.5);
        Cancion cc9 = new Cancion("Vas a quedarte", 9);
        Cancion cc10 = new Cancion("Lo malo", 7.5);
        Cancion cc11 = new Cancion("Fancy", 10);
        Cancion cc12 = new Cancion("Closer", 9);
        Cancion cc13 = new Cancion("Faded", 6.5);
        Cancion cc14 = new Cancion("Don't start now", 9.5);
        Cancion cc15 = new Cancion("Break my heart", 9);
        Cancion cc16 = new Cancion("Physical", 8);
        Cancion cc17 = new Cancion("Bad blood", 10);
        Cancion cc18 = new Cancion("Calm down", 9.5);
        Cancion cc19 = new Cancion("Blank space", 9.5);
        Cancion cc20 = new Cancion("Look what you made me do", 9);
        Cancion cc21 = new Cancion("End game", 8.5);
        Cancion cc22 = new Cancion("I knew you were trouble", 8.5);
        Cancion cc23 = new Cancion("ME!", 8.5);
        Cancion cc24 = new Cancion("Ready for it", 8);
        Cancion cc25 = new Cancion("Delicate", 7.5);
        Cancion cc26 = new Cancion("I don't wanna live forever", 7.5);
        Cancion cc27 = new Cancion("We are never ever getting back", 7.5);
        Cancion cc28 = new Cancion("Shake it off", 7);
        Cancion cc29 = new Cancion("Need you now", 9.5);
        Cancion cc30 = new Cancion("Side to side", 7);
        Cancion cc31 = new Cancion("Shallow", 8.5);
        Cancion cc32 = new Cancion("Timber", 8);
        Cancion cc33 = new Cancion("International love", 7.5);
        Cancion cc34 = new Cancion("Feel this moment", 7);
        Cancion cc35 = new Cancion("Dance again", 6.5);
        Cancion cc36 = new Cancion("Natural", 10);
        Cancion cc37 = new Cancion("Radioactive", 7.5);
        Cancion cc38 = new Cancion("Blinding lights", 6.5);
        Cancion cc39 = new Cancion("Wide awake", 10);
        Cancion cc40 = new Cancion("The one that got away", 10);
        Cancion cc41 = new Cancion("Never really over", 9.5);
        Cancion cc42 = new Cancion("Firework", 9);
        Cancion cc43 = new Cancion("California girls", 8);
        Cancion cc44 = new Cancion("Bon appétit", 7);
        Cancion cc45 = new Cancion("Perfect", 9.5);
        Cancion cc46 = new Cancion("Thinking out loud", 7.5);
        Cancion cc47 = new Cancion("Wake me up", 8);
        Cancion cc48 = new Cancion("Hey brother", 7);
        Cancion cc49 = new Cancion("Me too", 8);
        Cancion cc50 = new Cancion("No", 7);
        Cancion cc51 = new Cancion("No money", 8);
        Cancion cc52 = new Cancion("Can't hold us", 9);
        Cancion cc53 = new Cancion("Thrift shop", 8.5);
        Cancion cc54 = new Cancion("Animals", 9);
        Cancion cc55 = new Cancion("High hopes", 7);
        Cancion cc56 = new Cancion("Swalla", 8);
        Cancion cc57 = new Cancion("Want to want me", 7.5);
        Cancion cc58 = new Cancion("I have nothing", 8.5);
        Cancion cc59 = new Cancion("I will always love you", 7);
        Cancion cc60 = new Cancion("Love me like you do", 10);
        Cancion cc61 = new Cancion("Burn", 9.5);
        Cancion cc62 = new Cancion("Outside", 8);
        Cancion cc63 = new Cancion("Symphony", 9);
        Cancion cc64 = new Cancion("I really like you", 10);
        Cancion cc65 = new Cancion("Call me maybe", 7.5);
        Cancion cc66 = new Cancion("I'm a mess", 8);
        Cancion cc67 = new Cancion("Friends", 8.5);
        Cancion cc68 = new Cancion("Sueños rotos", 6.5);
        Cancion cc69 = new Cancion("Chandelier", 8.5);
        Cancion cc70 = new Cancion("Cheap thrills", 7);
        Cancion cc71 = new Cancion("Marvin Gaye", 9);
        Cancion cc72 = new Cancion("Attention", 8.5);
        Cancion cc73 = new Cancion("We don't talk anymore", 7.5);
        Cancion cc74 = new Cancion("Cheerleader", 6.5);
        Cancion cc75 = new Cancion("Some say", 7);
        Cancion cc76 = new Cancion("I need your love", 6.5);
        Cancion cc77 = new Cancion("Never forget you", 7);
        Cancion cc78 = new Cancion("Titanium", 6.5);
        Cancion cc79 = new Cancion("Rockabye", 6.5);
        Cancion cc80 = new Cancion("Lush life", 6.5);
        Cancion cc81 = new Cancion("It ain't my fault", 7);
        Cancion cc82 = new Cancion("Would you still love me the same", 6);
        Cancion cc83 = new Cancion("Welcome to my house", 6);
        Cancion cc84 = new Cancion("Wild ones", 6);
        Cancion cc85 = new Cancion("Impossible", 6);
        Cancion cc86 = new Cancion("Troublemaker", 6.5);

        c1.nuevaCancion(cc1);
        c1.nuevaCancion(cc2);
        c1.nuevaCancion(cc3);
        c1.nuevaCancion(cc4);
        c1.nuevaCancion(cc5);
        c1.nuevaCancion(cc6);
        c1.nuevaCancion(cc7);
        c1.nuevaCancion(cc8);
        c2.nuevaCancion(cc9);
        c2.nuevaCancion(cc10);
        c3.nuevaCancion(cc11);
        c4.nuevaCancion(cc12);
        c5.nuevaCancion(cc13);
        c6.nuevaCancion(cc14);
        c6.nuevaCancion(cc15);
        c6.nuevaCancion(cc16);
        c7.nuevaCancion(cc17);
        c7.nuevaCancion(cc18);
        c7.nuevaCancion(cc19);
        c7.nuevaCancion(cc20);
        c7.nuevaCancion(cc21);
        c7.nuevaCancion(cc22);
        c7.nuevaCancion(cc23);
        c7.nuevaCancion(cc24);
        c7.nuevaCancion(cc25);
        c7.nuevaCancion(cc26);
        c7.nuevaCancion(cc27);
        c7.nuevaCancion(cc28);
        c8.nuevaCancion(cc29);
        c9.nuevaCancion(cc30);
        c10.nuevaCancion(cc31);
        c11.nuevaCancion(cc32);
        c11.nuevaCancion(cc33);
        c11.nuevaCancion(cc34);
        c11.nuevaCancion(cc35);
        c12.nuevaCancion(cc36);
        c12.nuevaCancion(cc37);
        c13.nuevaCancion(cc38);
        c14.nuevaCancion(cc39);
        c14.nuevaCancion(cc40);
        c14.nuevaCancion(cc41);
        c14.nuevaCancion(cc42);
        c14.nuevaCancion(cc43);
        c14.nuevaCancion(cc44);
        c15.nuevaCancion(cc45);
        c15.nuevaCancion(cc46);
        c16.nuevaCancion(cc47);
        c16.nuevaCancion(cc48);
        c17.nuevaCancion(cc49);
        c17.nuevaCancion(cc50);
        c18.nuevaCancion(cc51);
        c19.nuevaCancion(cc52);
        c19.nuevaCancion(cc53);
        c20.nuevaCancion(cc54);
        c21.nuevaCancion(cc55);
        c22.nuevaCancion(cc56);
        c22.nuevaCancion(cc57);
        c23.nuevaCancion(cc58);
        c23.nuevaCancion(cc59);
        c24.nuevaCancion(cc60);
        c24.nuevaCancion(cc61);
        c24.nuevaCancion(cc62);
        c25.nuevaCancion(cc63);
        c26.nuevaCancion(cc64);
        c26.nuevaCancion(cc65);
        c27.nuevaCancion(cc66);
        c28.nuevaCancion(cc67);
        c29.nuevaCancion(cc68);
        c30.nuevaCancion(cc69);
        c30.nuevaCancion(cc70);
        c31.nuevaCancion(cc71);
        c31.nuevaCancion(cc72);
        c31.nuevaCancion(cc73);
        c32.nuevaCancion(cc74);
        c33.nuevaCancion(cc75);
        c24.nuevaCancion(cc76);
        c35.nuevaCancion(cc77);
        c34.nuevaCancion(cc78);
        c25.nuevaCancion(cc79);
        c35.nuevaCancion(cc80);
        c35.nuevaCancion(cc81);
        c39.nuevaCancion(cc82);
        c37.nuevaCancion(cc83);
        c37.nuevaCancion(cc84);
        c36.nuevaCancion(cc85);
        c38.nuevaCancion(cc86);


        l.mostrar();

        l.mostrarCantante(23);
    }
}